import React, { useState, useEffect, useRef } from 'react';
import { X, Send, ChevronRight, CheckCircle2 } from 'lucide-react';
import './KaizenAssistant.css';

// ── Complete Knowledge Base ──────────────────────────────────────────────────
const KNOWLEDGE = {
  identity: `Ajaz Mohemmed S is a final-year B.Tech student specialising in Artificial Intelligence and Machine Learning at Christ (Deemed to be) University, Bangalore (2022–2026). His work focuses on intelligent systems, AI assistants, generative AI research, and full-stack AI development.`,

  education: `🎓 Education:\n\n1. B.Tech – Artificial Intelligence and Machine Learning\n   Christ (Deemed to be) University, Bangalore | 2022 – 2026\n\n2. Higher Secondary (HSC)\n   Puliyaparamb Higher Secondary School, Palakkad | 2020 – 2022`,

  research: `🔬 Published Research (SCIS 2025 – Springer):\n\nDecision Flow Tracing and Word Impact Analysis in Hybrid Transformer-Conditioned Diffusion Models for Text-to-Image Generation.\n\n*What it means:* This research focuses on understanding how words in prompts influence images generated by diffusion models. It proposes a hybrid architecture combining UNet diffusion models with transformer cross-attention blocks and introduces explainability techniques such as token attention heatmaps, temporal attention rollouts, and semantic ablation analysis.\n\nAuthors: Ajaz Mohemmed S, Aldrin P Thomas, Shiju George, N Anand Raj, Mdhun Shaju, Akil Nasim.`,

  ongoing_research: `🛡️ Current Research Work:\n\nDesign and Experimental Evaluation of Secure Multimodal Interaction in a Privacy-Centered, Offline-First Personal AI Voice Assistant.\n\n*What it means:* Exploring the design of a privacy-preserving AI voice assistant that works primarily offline. It supports secure multimodal interaction (voice, text, and contextual inputs) with a heavy focus on user privacy, local processing of sensitive data, secure command execution, and reduced cloud dependence. The goal is a trustworthy, highly capable AI that prioritizes user data protection.`,

  experience: `💼 Experience:\n\n1. Python Intern @ Cognifyz (Apr–May 2024)\n   - Built an ML system predicting restaurant ratings (35% better accuracy).\n   - Automated 95% of the ML pipeline (scikit-learn, Pandas, NumPy).\n\n2. Intern @ TrizLabs (Jun–Sep 2024)\n   - Designed an infrared monocular depth estimation system for robotics and surveillance.`,

  nora: `🤖 About NORA (Neural Operated Residential Assistant):\n\nNORA is a full-stack AI personal assistant platform that integrates conversational intelligence with real-time backend task execution. \n\nIt supports multi-modal inputs (text, voice, documents, URLs, code) and includes modules for document summarization, system monitoring, music playback, code review, and intelligent web search. NORA is built using Python, Flask, REST APIs, and large language model reasoning.`,

  projects: `🚀 Key Projects:\n\n1. NORA: Full-stack AI residential assistant (Python, Flask, multimodal agentic AI).\n2. Personal Voice Assistant: NLP-powered, hands-free voice AI running locally.\n3. Business Intelligence Agent: AI agent answering founder-level business queries integrating with monday.com boards (Demo: monday-bi-agent-nlp9.onrender.com).`,

  skills: `🛠️ Skills & Expertise:\n\n- Artificial Intelligence\n- Machine Learning\n- Deep Learning\n- DSA\n- Generative AI\n- Large Language Models\n- Computer Vision\n- Python\n- Flask\n- REST API Development\n- AI System Design`,

  certifications: `🏅 Certifications:\n\n1. Data Science for Engineers – NPTEL (IIT Madras)\n2. AWS Academy Cloud Foundation\n3. Cybersecurity Training (Hands-on ethical hacking) – Cisco`,

  volunteering: `🤝 Volunteering & Leadership:\n\n1. Media Vice Head @ CUESTIC (Christ University): Grew from media volunteer to Vice Head handling photography/videography.\n2. Volunteer @ NSS: Participated in environmental projects and cleanliness drives.`,

  contact: `📞 Contact & Collaboration:\n\nAjaz is always open to collaborative opportunities and roles in AI Engineering!\n\nPhone: +91 7306587895\nEmail: ajazmohemmeds@gmail.com\nLinkedIn: [Available on the Contact page]`
};

// ── Local Rule-Based Engine ─────────────────────────────────────────────────
const generateLocalResponse = (input) => {
  const text = input.toLowerCase();
  
  // Greetings
  if (text.match(/\b(hi|hello|hey|greetings|morning|afternoon)\b/)) {
    return "Hello! 👋 I'm Kaizen, Ajaz's personal AI representative. I can tell you all about his expertise in Generative AI, his NORA architecture, diffusion research, and technical skills. What would you like to explore?";
  }

  // Identity / Who is he?
  if (text.match(/who is|about (ajaz|him)|tell me about ajaz/)) {
    return KNOWLEDGE.identity;
  }

  // NORA Specific
  if (text.match(/nora|residential assistant|neural operated/)) {
    return KNOWLEDGE.nora;
  }

  // Research (Diffusion / SCIS 2025)
  if (text.match(/diffusion|scis|transformer|word impact|publish|paper|text-to-image/)) {
    return KNOWLEDGE.research;
  }

  // Ongoing Research (Secure Voice AI)
  if (text.match(/ongoing|current|secure voice|offline-first|privacy|multimodal/)) {
    return KNOWLEDGE.ongoing_research;
  }

  // Education
  if (text.match(/education|study|studied|degree|college|university|school/)) {
    return KNOWLEDGE.education;
  }

  // Experience / Internships
  if (text.match(/experience|\bwork\b|intern|internship|cognifyz|trizlabs/)) {
    return KNOWLEDGE.experience;
  }

  // Projects General
  if (text.match(/project|build|built|business intelligence|bi agent|monday\.com/)) {
    return KNOWLEDGE.projects;
  }

  // Skills & Technologies
  if (text.match(/skill|tech|programming|language|framework|python|react|flask|api|llm/)) {
    return KNOWLEDGE.skills;
  }

  // Certifications
  if (text.match(/cert|nptel|aws|cisco|certificate/)) {
    return KNOWLEDGE.certifications;
  }

  // Volunteering & Extracurriculars
  if (text.match(/volunteer|nss|cuestic|extra|club|leadership/)) {
    return KNOWLEDGE.volunteering;
  }

  // Contact / Collaboration / Recruiters
  if (text.match(/contact|phone|email|number|call|reach|hire|collaborate|recruit/)) {
    return KNOWLEDGE.contact;
  }

  // Fallback
  return "That's a great question! While I can't generate a dynamic answer for that right now I highly recommend asking me to Explain the NORA project tell you about his Diffusion Research or list his AI System Design skills!";
};

const KaizenAssistant = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    { role: 'assistant', text: "Hello! 👋 I'm Kaizen Ajaz's personal AI representative. I'm here to help visitors recruiters and collaborators learn about his AI projects diffusion research and engineering skills. How can I help you today?", type: 'message' }
  ]);
  const [input, setInput] = useState('');
  const [isThinking, setIsThinking] = useState(false);
  const [thoughtSteps, setThoughtSteps] = useState([]);
  const messagesEndRef = useRef(null);
  
  // Retaining the original icon variable but using NORA context
  const kaizenIcon = `${import.meta.env.BASE_URL}images/kaizen_icon.png`;

  // Handle Cmd+K or Ctrl+K shortcut
  useEffect(() => {
    const handleKeyDown = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'k') {
        e.preventDefault();
        setIsOpen(prev => !prev);
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, thoughtSteps]);

  const handleSend = async (text) => {
    if (!text.trim() || isThinking) return;

    setMessages(prev => [...prev, { role: 'user', text, type: 'message' }]);
    setInput('');
    setIsThinking(true);
    setThoughtSteps([
      { id: 1, label: "Analyzing intent...", status: "pending" },
      { id: 2, label: "Scanning portfolio knowledge...", status: "pending" },
      { id: 3, label: "Synthesizing response...", status: "pending" }
    ]);

    // Simulate thinking time for a natural conversational flow
    setTimeout(() => {
      setThoughtSteps(prev => prev.map(s => s.id === 1 ? { ...s, status: 'complete' } : s));
    }, 400);

    setTimeout(() => {
      setThoughtSteps(prev => prev.map(s => s.id === 2 ? { ...s, status: 'complete' } : s));
    }, 900);

    setTimeout(() => {
      // Remove hyphens and commas from the response text
      const rawResponse = generateLocalResponse(text);
      const cleanResponse = rawResponse.replace(/[,-]/g, '');
      setThoughtSteps(prev => prev.map(s => s.id === 3 ? { ...s, status: 'complete' } : s));
      
      setTimeout(() => {
        setMessages(prev => [...prev, { role: 'assistant', text: cleanResponse, type: 'message' }]);
        setIsThinking(false);
        setThoughtSteps([]);
      }, 400);
    }, 1400);
  };

  // If not open, render nothing since trigger button is removed
  if (!isOpen) return null;

  return (
    <div className={`kaizen-widget ${isOpen ? 'open' : ''}`}>
      <div className="kaizen-chat-window">
        <div className="kaizen-header">
          <div className="kaizen-title">
            <img src={kaizenIcon} alt="Kaizen" className="kaizen-icon-img small" />
            <span>Ask Kaizen</span>
          </div>
          <button className="kaizen-close" onClick={() => setIsOpen(false)}><X size={20} /></button>
        </div>

          <div className="kaizen-messages">
            {messages.map((msg, i) => (
              <div key={i} className={`message-bubble ${msg.role}`}>
                <div className="bubble-text" style={{ whiteSpace: 'pre-wrap' }}>{msg.text}</div>
              </div>
            ))}
            {isThinking && (
              <div className="thought-process">
                <div className="thought-header">
                  <div className="thinking-dots"><span></span><span></span><span></span></div>
                  <span>Kaizen is thinking...</span>
                </div>
                <div className="thought-steps">
                  {thoughtSteps.map(step => (
                    <div key={step.id} className={`thought-step ${step.status}`}>
                      {step.status === 'complete' ? <CheckCircle2 size={12} /> : <ChevronRight size={12} />}
                      <span>{step.label}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className="kaizen-quick-prompts">
            <button onClick={() => handleSend("Explain the NORA project")}>NORA Architecture</button>
            <button onClick={() => handleSend("Explain Ajaz's diffusion research")}>Diffusion Research</button>
            <button onClick={() => handleSend("What research is Ajaz currently working on?")}>Current Research</button>
            <button onClick={() => handleSend("What technologies does Ajaz use?")}>Tech Stack</button>
            <button onClick={() => handleSend("How can I contact Ajaz?")}>Contact</button>
          </div>

          <form className="kaizen-input-area" onSubmit={(e) => { e.preventDefault(); handleSend(input); }}>
            <input
              type="text"
              placeholder="Ask Kaizen about Ajaz..."
              value={input}
              onChange={(e) => setInput(e.target.value)}
            />
            <button type="submit" disabled={!input.trim() || isThinking}><Send size={18} /></button>
          </form>
      </div>
    </div>
  );
};

export default KaizenAssistant;
